import random
'''
🌟 Exercise 1 : What are you learning ?
Instructions
1. Write a function called display_message() that prints one sentence telling everyone what you are learning in this course.
2. Call the function, and make sure the message displays correctly.

'''


# def display_message():
#     print("Hey everyone!\nWe're learning about functions in python 🐍 ")

# display_message()

'''
🌟 Exercise 2: What's your favorite book ?
Instructions
1. Write a function called favorite_book() that accepts one parameter called title.
2. The function should print a message, such as "One of my favorite books is <title>".
For example: “One of my favorite books is Alice in Wonderland”
3. Call the function, make sure to include a book title as an argument when calling the function.
'''

# def favourite_book(title:str):
#     print(f'One of my favorite books is {title.title()}."')

# favourite_book('To kill a mockingbird')

# #or

# favourite_book(title = "harry potter")

'''
🌟 Exercise 3 : Some Geography
Instructions
1. Write a function called describe_city() that accepts the name of a city and its country as parameters.
2. The function should print a simple sentence, such as "<city> is in <country>".
For example “Reykjavik is in Iceland”
3. Give the country parameter a default value.
4. Call your function.
'''

# def describe_city(city_name, country):
#     print(f"{city_name.capitalize()} is in {country.capitalize()}.")

# describe_city('montreal', 'canada')

'''
🌟Exercise 4 : Random
Instructions
Create a function that accepts a number between 1 and 100 and generates another number randomly between 1 and 100. Use the random module.
Compare the two numbers, if it's the same number, display a success message, otherwise show a fail message and display both numbers.
'''


# def compare_rand_to_rand(number:int):
#     '''compare a random int to another random int (generated by function)'''
#     rand  = random.randint(1,100)
#     if  1 > number > 100:
#         print("not between 1 & 100")
#         return
#     elif number == rand:
#         print("Awesome 🍀")
#     else: print(f"Fail... {number} not equal to {rand} 👻")

# rand_int_100 = random.randint(1,100)

# compare_rand_to_rand(rand_int_100)

'''
🌟 Exercise 5 : Let's create some personalized shirts !
Instructions
1. Write a function called make_shirt() that accepts a size and the text of a message that should be printed on the shirt.
2. The function should print a sentence summarizing the size of the shirt and the message printed on it, such as "The size of the shirt is <size> and the text is <text>"
3. Call the function make_shirt().
4. Modify the make_shirt() function so that shirts are large by default with a message that reads “I love Python” by default.
5. Call the function, in order to make a large shirt with the default message
6. Make medium shirt with the default message
7. Make a shirt of any size with a different message.

Bonus: Call the function make_shirt() using keyword arguments.
'''

# def make_shirt(size:str = "large", text:str = "I Love Python 🐍"):
#     print(f"The size of the shirt is {size} and the text is {text}.")
# #3 - #7
# make_shirt("small","I love Java Script 🤖")
# make_shirt("large")
# make_shirt("")
# make_shirt("medium")
# make_shirt(text = "Hello world", size="small")

'''
🌟 Exercise 6 : Magicians …
Instructions
Using this list of magician's names

magician_names = ['Harry Houdini', 'David Blaine', 'Criss Angel']

1. Create a function called show_magicians(), which prints the name of each magician in the list.
2. Write a function called make_great() that modifies the original list of magicians by adding the phrase "the Great" to each magician's name.
3. Call the function make_great().
4. Call the function show_magicians() to see that the list has actually been modified.
'''
#1
# magician_names = ['Harry Houdini', 'David Blaine', 'Criss Angel']

# # def show_magicians(magician_list):
# #     for magician in magician_names:
# #         print(magician)

# # show_magicians(magician_names)
# #2
# def make_great(magician_names):
#     for i in range(len(magician_names)):
#         magician_names[i] += " the great"

# make_great(magician_names)
# print(magician_names)

'''
🌟 Exercise 7 : Temperature Advice

1. Create a function called get_random_temp().
This function should return an integer between -10 and 40 degrees (Celsius), selected at random.
Test your function to make sure it generates expected results.

2. Create a function called main().
Inside this function, call get_random_temp() to get a temperature, and store its value in a variable.
Inform the user of the temperature in a friendly message, eg. “The temperature right now is 32 degrees Celsius.”

3. Let's add more functionality to the main() function. Write some friendly advice relating to the temperature:
below zero (eg. “Brrr, that's freezing! Wear some extra layers today”)
between zero and 16 (eg. “Quite chilly! Don't forget your coat”)
between 16 and 23
between 24 and 32
between 32 and 40

4. Change the get_random_temp() function:
Add a parameter to the function, named 'season'.
Inside the function, instead of simply generating a random number between -10 and 40, set lower and upper limits based on the season, eg. if season is 'winter', temperatures should only fall between -10 and 16.
Now that we've changed get_random_temp(), let's change the main() function:
Before calling get_random_temp(), we will need to decide on a season, so that we can call the function correctly. Ask the user to type in a season - 'summer', 'autumn' (you can use 'fall' if you prefer), 'winter', or 'spring'.
Use the season as an argument when calling get_random_temp().

5. Bonus: Give the temperature as a floating-point number instead of an integer.
6.Bonus: Instead of asking for the season, ask the user for the number of the month (1 = January, 12 = December). Determine the season according to the month.
'''
#1 #4 #5
# def get_random_temp(season:str):
#     if season == "summer":
#         temp = round(random.uniform(20,40),1)
#     elif season == "fall":
#         temp = round(random.uniform(13,20),1)
#     elif season == "winter":
#         temp = round(random.uniform(-10,16),1)
#     elif season == "spring":
#         temp = round(random.uniform(15,20),1)
#     return temp

# def get_random_temp(month:int):
#     if month == 12 or month <= 2 :
#         temp = round(random.uniform(20,40),1)
#     elif 6 <= month <= 9 :
#         temp = round(random.uniform(13,20),1)
#     elif 10 <= month <= 11 :
#         temp = round(random.uniform(-10,16),1)
#     elif 3 <= month <= 5 :
#         temp = round(random.uniform(15,20),1)
#     return temp

# #2 #3 
# def main(season:str):
#     rand_temp = get_random_temp(season)
#     print(f"The temperature right now is {rand_temp} Celsius \n")
#     if 0 > rand_temp:
#         print(f"Brrr, that's freezing! Wear some extra layers today! 🥶")
#     elif 0 <= rand_temp <= 16:
#         print(f"Quite chilly! Don't forget your coat! 🌨️")
#     elif 16 < rand_temp <= 23:
#         print(f"Juuuust right! 😎")
#     elif 23 < rand_temp <= 32:
#         print(f"it's Hot and allright! ⛱️")
#     elif 32 < rand_temp <= 40:
#         print(f"beach timee!!!🏖️")

# # usr_season = input("please enter a season: \n")
# # main(usr_season)\
# #6
# usr_month = int(input("please enter a month (1-12): \n"))
# main(usr_month)

'''
🌟 Exercise 8 : Star Wars Quiz
Instructions
This project allows users to take a quiz to test their Star Wars knowledge.
The number of correct/incorrect answers are tracked and the user receives different messages depending on how well they did on the quiz.

Here is an array of dictionaries, containing those questions and answers


Create a function that asks the questions to the user, and check his answers. Track the number of correct, incorrect answers. Create a list of wrong_answers
Create a function that informs the user of his number of correct/incorrect answers.
Bonus : display to the user the questions he answered wrong, his answer, and the correct answer.
If he had more then 3 wrong answers, ask him to play again.
'''
data = [
    {
        "question": "What is Baby Yoda's real name?",
        "answer": "Grogu"
    },
    {
        "question": "Where did Obi-Wan take Luke after his birth?",
        "answer": "Tatooine"
    },
    {
        "question": "What year did the first Star Wars movie come out?",
        "answer": "1977"
    },
    {
        "question": "Who built C-3PO?",
        "answer": "Anakin Skywalker"
    },
    {
        "question": "Anakin Skywalker grew up to be who?",
        "answer": "Darth Vader"
    },
    {
        "question": "What species is Chewbacca?",
        "answer": "Wookiee"
    }
]


#1
def ask_question(data):
    print("---Quizz Start---")
    wrong_ans_list = []
    right_ans_list = []
    true_ans_list = []
    for dicts in range(len(data)):
        usr_ans = input(data[dicts]["question"])
        true_ans = data[dicts]["answer"]
        if usr_ans != true_ans:
            wrong_ans_list.append(usr_ans)
            true_ans_list.append(true_ans)
        else:right_ans_list.append(usr_ans)
    print("---Quizz End---")
    return wrong_ans_list, right_ans_list, true_ans_list
#for some reason if aswers are wrong it repeats only once I dontknow why ...
#2 #3 #bonus
def quizz_report(wrong, right, true):
    print("----Quizz Report---")
    wrong_str = ", ".join(wrong)
    right_str = ", ".join(right)
    true_str = ", ".join(true)
    print(f"You got {len(wrong)} wrong answers and {len(right)} right answers.")
    print(f"Your wrong answers where : {wrong_str}")
    print(f"Your wrong answers where : {right_str}")
    print(f"the true answers where: {true_str}")
    if len(wrong) > 3:
        print("-----:Start Again:-----")
        ask_question(data)
    else: print("May the force be with you!")


wrongs, rights, true = ask_question(data)   
quizz_report(wrongs, rights, true)

    

